#!/usr/bin/env bash


install_spacemacs(){
  echo "Install Spacemacs"
  git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
  echo "Configure custom spacemacs"
  git clone git@github.com:ecamalionte/dotspacemacs.git ~/
  ln -s ~/dotspacemacs/.spacemacs ~/.spacemacs
}

install_zshell() {
  echo "Install Zsh"
  sudo apt install zsh -y
  #sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

install_sintax_highlighting() {
  echo "Install Zsh Sintax Highlighting"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
}

install_completion() {
  echo "Install Zsh Completion"
  git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
}

install_auto_suggestion() {
  echo "Install Zsh Auto Suggestion"
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
}

install_asdf() {
  echo "Install ASDF Version Manager"
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
}

apply_configuration() {
  echo "Apply ZSH configurations"
  cp ./_zshrc ~/.zshrc
}

add_asdf_plugins_for_elixir_and_erlang() {
  echo "Install ASDF Elixir/Erlang OTP plugin"
  asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git

  echo "Install Erlang Compile dependencies"
  sudo apt install automake -y
  sudo apt install autoconf -y
  sudo apt install libncurses5-dev -y
}

add_asdf_plugins_for_ruby() {
  echo "Install ASDF Ruby plugins"
  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
}

install_tmux() {
  echo "Install Tmux"
  sudo apt install tmux -y
}

install_ruby() {
  asdf install ruby 2.6.5
  asdf global ruby 2.6.5
}

install_tmuxinator() {
  sudo apt install libreadline-dev
  gem install tmuxinator
}

configure_git() {
  git config --global user.email "ecamalionte@gmail.com"
  git config --global user.name "Eric Camalionte"
  # generate_ssh_private_and_public_key
}

generate_ssh_private_and_public_key() {
  ssh-keygen -t rsa -b 4096 -C "ecamalionte@gmail.com"
  cat ~/.ssh/id_rsa.pub
}

install_docker() {
  sudo curl -sSL https://get.docker.com | sh
  sudo usermod -aG docker pi
  doker ps
}

install_docker_compose() {
  sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  docker-compose --version
}

install_pgcli() {
  sudo apt install python-dev
  sudo apt install libpq-dev
  export PATH=/usr/lib/postgresql/X.Y/bin/:$PATH
  pip install psycopg2
  pip install pgcli
  pgcli -v
}

main() {
  sudo apt update
  configure_git
  install_spacemacs
  install_zshell
  install_sintax_highlighting
  install_completion
  install_auto_suggestion
  install_asdf
  apply_configuration
  add_asdf_plugins_for_elixir_and_erlang
  add_asdf_plugins_for_ruby
  install_tmux
  install_ruby
  install_tmuxinator
  install_docker
  install_docker_compose
  install_pgcli
}

main
